### ISSUE TITLE
Table Structure

### ISSUE THREAD

**Issue by RRavage** [DoubleRepo/vRP_Properties#1]
Hey is there any chance of getting a SQL table structure for this? I was hoping to add some things to this for my server and would push it back to you with any changes if you wanted to utilize them

**Comment by DoubleRepo** [comment]
Hi,

This is a unfinished project. Since it's only suppose to be used by people that have a decent amount of knowledge about lua / programming in general i didn't release the MySql database structure yet.

One can create the tables from reading how this resources interacts with the database if you really want to use this.

However, this is a unfinished project with no config and componements for it on this git.
You are not being able to use it that way.

DoubleRepo

/closed

**Comment by RRavage** [comment]
Thanks for the reply - however I do have LUA knowledge and I am not simply looking to plug this in to play. I operate on a highly modified version of VRPEX. 

I was going to push you back changes in an effort to help you with the resource, I just couldn't make this work and assumed there was something I missed from the table structure. 

I however respect your decision not to share the structure.

**Comment by DoubleRepo** [comment]
This is actually made for the version "vrp" before "vrpex".
